#!/bin/bash

echo "=== Cloudinary Setup Instructions ==="
echo ""
echo "1. Go to https://cloudinary.com and sign up/login"
echo "2. In your dashboard, you'll find these credentials:"
echo "   - Cloud Name"
echo "   - API Key" 
echo "   - API Secret"
echo ""
echo "3. Create an upload preset:"
echo "   - Go to Settings > Upload"
echo "   - Click 'Add upload preset'"
echo "   - Set name to: unsigned_preset"
echo "   - Set Signing Mode to: Unsigned"
echo "   - Set folder to: profile_pictures"
echo "   - Add transformation: c_fill,w_300,h_300,f_auto,q_auto"
echo "   - Save"
echo ""
echo "4. Add these environment variables to your shell:"
echo ""
echo "export CLOUDINARY_CLOUD_NAME=\"your_cloud_name_here\""
echo "export CLOUDINARY_API_KEY=\"your_api_key_here\""
echo "export CLOUDINARY_API_SECRET=\"your_api_secret_here\""
echo ""
echo "5. Or add them to a .env file in the backend directory:"
echo ""
echo "CLOUDINARY_CLOUD_NAME=your_cloud_name_here"
echo "CLOUDINARY_API_KEY=your_api_key_here"
echo "CLOUDINARY_API_SECRET=your_api_secret_here"
echo ""
echo "6. Then restart your backend server with these environment variables"
